### ISSUE TITLE
package.json Missing Scripts & Associated .env Files

### ISSUE THREAD

**Issue by PnxBlue** [multiversx/mx-dex-screener-adapter-service#14]
In the Package.json the following scripts are in place:
start:api:mainnet
start:api:custom
start:offline-jobs:mainnet
start:offline-jobs:custom
![image](https://github.com/multiversx/mx-dex-screener-adapter-service/assets/164737012/13eeda6c-2e3d-4b79-bde6-d393d9319050)

The readme.md states 

```
# development watch mode on devnet
$ npm run start:devnet:watch

# development debug mode on devnet
$ npm run start:devnet:debug

# development mode on devnet
$ npm run start:devnet

# production mode
$ npm run start:mainnet
```

One extra note is that the current start script references .env.mainnet and .env.custom files, which aren't included in the source.

As a result, it's not possible to start up the app, based on the instructions on the readme

**Comment by gabrielmatei** [comment]
thanks for reporting the issue. The README file was updated in https://github.com/multiversx/mx-dex-screener-adapter-service/pull/16
